---
- hosts: ping-2
  gather_facts: true
  #become: yes

  vars:
    grant_sudo: ttest

  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /var/local/adm
        state: directory
        mode: '0755'

    - name: Run a script with arguments (using 'cmd' parameter)
      command: /bin/bash -c "echo "{{ grant_sudo }}" >> /golang/vggansible/adm/users"
    
    - name: Clone a github repository
      git:
        repo: https://github.com/yommy-fakorede/ansible-test.git
        dest: /var/local/adm/
        clone: yes
        update: yes

    - name: Execute script
      command: sh add_ldap_users.sh
      args:
        chdir: /var/local/adm/

    - name: grant sudo access to user
      ansible.builtin.script:
        cmd: "usermod -aG sudo {{ grant_sudo }}"
      ignore_errors: true
      when: ansible_os_family == "Debian"

    - name: grant sudo access to user
      ansible.builtin.script:
        cmd: "usermod -aG wheel {{grant_sudo}}"
      ignore_errors: true
      when: ansible_os_family == "RedHat"

    - name: grant sudo access to user
      ansible.builtin.script:
        cmd: "usermod -aG wheel {{grant_sudo}}"
      ignore_errors: true
      when:
        - ansible_distribution == "CentOS"
